name: Release Terraform Module

on:
  workflow_dispatch:
    inputs:
      module_name:
        description: Name of the module to release, must exist in modules/ dir
        required: true
        type: string
      version:
        description: Version of the module to release. Should adhere to semantic versioning ("M.m.p")
        required: true
        type: string

env:
  TEMP_BRANCH_NAME: temp-branch

jobs:
  release-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0 # fetch entire history

      - name: Validate input module name
        run: |
          if [ ! -d "modules/${{ inputs.module_name }}" ]; then
            echo "Error: Module '${{ inputs.module_name }}' does not exist!"
            exit 1
          fi

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create temporary branch
        run: git checkout --orphan ${{ env.TEMP_BRANCH_NAME }}

      - name: Remove all files
        run: git rm -rf .

      - name: Copy module to root
        run: |
          git checkout main -- modules/${{ inputs.module_name }}
          mv modules/${{ inputs.module_name }}/* .
          rm -rf modules

      - name: Commit module files
        run: |
          git add .
          git commit -m "(CI) Release ${{ inputs.module_name }} v${{ inputs.version }}"

      - name: Create and push tag
        run: |
          TAG_NAME="${{ inputs.module_name }}/v${{ inputs.version }}"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean temporary branch
        if: always()
        run: |
          git checkout main
          git branch -D ${{ env.TEMP_BRANCH_NAME }} || true
